apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 801490935459.dkr.ecr.ap-south-1.amazonaws.com/frontend:6
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://api.three-tier.svc.cluster.local:3500/api/tasks"       #http://k8s-three-...elb.amazonaws.com/api/tasks  if you want to use alb to access /api/tasks endpoint
        ports:
        - containerPort: 3000
